namespace: "mateothegreat"
name: "redis_latest"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Install & configure the latest version of redis."
license: ["MIT"]
license_file: "COPYING"
tags: ["redis"]
repository: "https://github.com/mateothegreat/redis-latest.git"
homepage: "https://github.com/mateothegreat/redis-latest"
issues: "https://github.com/mateothegreat/redis-latest/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
